# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=8)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Persona')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('PrecioCompra', models.DecimalField(decimal_places=2, max_digits=20)),
                ('PecioVenta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Igv', models.DecimalField(decimal_places=2, max_digits=20)),
                ('detalle', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Categoria')),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='unidadesmedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnidadMedida', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Unidades de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidadM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.unidadesmedida'),
        ),
    ]
