# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20170627_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='PrecioCompra',
            new_name='precioCompra',
        ),
        migrations.RenameField(
            model_name='unidadesmedida',
            old_name='UnidadMedida',
            new_name='unidadMedida',
        ),
        migrations.AddField(
            model_name='unidadesmedida',
            name='prefijo',
            field=models.CharField(default='Kg', max_length=20),
            preserve_default=False,
        ),
    ]
