# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20170627_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='unidadM',
            new_name='unidadMedida',
        ),
    ]
