# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fech_acopio', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Acopios',
                'verbose_name': 'Acopio',
            },
        ),
        migrations.CreateModel(
            name='AcopioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.IntegerField()),
                ('precio_uni', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'AcopioDetalles',
                'verbose_name': 'AcopioDetalle',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('ubicacion', models.CharField(max_length=20)),
                ('area_cultivo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('area_desarrollo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prod_estimado_tn', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prod_estimado_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('certificacion_propuesta', models.CharField(max_length=5)),
                ('total_parcelas', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Parcelas',
                'verbose_name': 'Parcela',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_socio', models.CharField(max_length=6)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acopio.Parcela')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Person')),
            ],
            options={
                'verbose_name_plural': 'Socios',
                'verbose_name': 'Socio',
            },
        ),
        migrations.AddField(
            model_name='acopio',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acopio.Socio'),
        ),
    ]
