# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
