# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='total_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
