# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='area_cultivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='area_desarrollo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='prod_estimado_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='prod_estimado_tn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
