# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0002_socio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acopio.Socio'),
            preserve_default=False,
        ),
    ]
