# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0003_parcela_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='area_cultivo',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='area_desarrollo',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
