# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReciboHonorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=20)),
                ('suma_de', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_neto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'DetalleReciboHonorario',
                'verbose_name_plural': 'DetalleReciboHonorarios',
            },
        ),
        migrations.CreateModel(
            name='PagoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'PagoPersonal',
                'verbose_name_plural': 'PagoPersonales',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('mes_correspondiente', models.CharField(max_length=20)),
                ('pago_total', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personales',
            },
        ),
        migrations.CreateModel(
            name='PersonalRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('RUC', models.CharField(max_length=20)),
                ('pagopersonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagopersonal.PagoPersonal')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Persona')),
            ],
            options={
                'verbose_name': 'PersonalRegistro',
                'verbose_name_plural': 'PersonalRegistros',
            },
        ),
        migrations.CreateModel(
            name='ReciboHonorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('num_recibo_honorarios', models.CharField(max_length=20)),
                ('detalle_recibo_honorarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagopersonal.DetalleReciboHonorario')),
            ],
            options={
                'verbose_name': 'ReciboHonorario',
                'verbose_name_plural': 'ReciboHonorarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RegistroAsistencia',
                'verbose_name_plural': 'RegistroAsistencias',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='personal_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagopersonal.PersonalRegistro'),
        ),
        migrations.AddField(
            model_name='personal',
            name='registro_asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagopersonal.RegistroAsistencia'),
        ),
        migrations.AddField(
            model_name='detallerecibohonorario',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagopersonal.Personal'),
        ),
    ]
